// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHjEdFrll8mlt_L_MnQcnrGAdt6QEoa6I',
    appId: '1:731938048409:android:72ab5c7932b4304aa1eb08',
    messagingSenderId: '731938048409',
    projectId: 'jeusetmatch-ed051',
    storageBucket: 'jeusetmatch-ed051.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrprLVM_V8wDkBUMXNtVlgfahy70yRQV0',
    appId: '1:731938048409:ios:cd4321c81e3b4f3ca1eb08',
    messagingSenderId: '731938048409',
    projectId: 'jeusetmatch-ed051',
    storageBucket: 'jeusetmatch-ed051.firebasestorage.app',
    iosBundleId: 'com.development.jeusetmatch2',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzkqFNy9jVbUrRpCGXGEqk4GHL3qSA0fs',
    appId: '1:731938048409:web:a57f59c652de392fa1eb08',
    messagingSenderId: '731938048409',
    projectId: 'jeusetmatch-ed051',
    authDomain: 'jeusetmatch-ed051.firebaseapp.com',
    storageBucket: 'jeusetmatch-ed051.firebasestorage.app',
    measurementId: 'G-FTPPZ11XNB',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzkqFNy9jVbUrRpCGXGEqk4GHL3qSA0fs',
    appId: '1:731938048409:web:f872f9276e153f28a1eb08',
    messagingSenderId: '731938048409',
    projectId: 'jeusetmatch-ed051',
    authDomain: 'jeusetmatch-ed051.firebaseapp.com',
    storageBucket: 'jeusetmatch-ed051.firebasestorage.app',
    measurementId: 'G-RHV352LK13',
  );

}